### ISSUE TITLE
BIDS-ephys: let's BIDSify your animal electrophysiology data

### ISSUE THREAD

**Issue by SylvainTakerkart** [Brainhack-Marseille/brainhack-marseille.github.io#11]
## Project info

**Title:**
BIDS-ephys: let's BIDSify your animal electrophysiology data

**Project lead and collaborators:**
Sylvain Takerkart & Julia Sprenger (coordinators of the BIDS-extension proposal for animal electrophysiology)
Other members of the INCF working group on Neuroscience Data Structure

**Description:**

We are working on an extension proposal so that BIDS (a standardized data structure described here: https://bids.neuroimaging.io/ ) can support electrophysiological data recorded in animal models. Our working document that describes the data organization for animal ephys data is available here: https://bids.neuroimaging.io/bep032 . It is now ready to be used, and we propose here that electrophysiologists can attempt applying this organization to their data, with the help of the community.

**Goals for Brainhack Marseille**
- Have as many electrophysiologists as possible convert their data to the proposed BIDS-ephys organization.
- Identify potential problems in the specifications, solve them.
- Make progress on the tools required to facilitate this conversion (some of them being present in https://github.com/INT-NIT/AnDO/)

**Skills:**
Different types of people and skills will be useful:
- [non-coding] eletrophysiologists to bring expertise on their data and its description (i.e: just bring your data and we'll work on it together!!!)
- [non-coding] BIDS enthusiasts (or experts) to make progress on the specification document
- [coding] python programmers to make progress on the tools

**Striking Image**

![neuron_morpho](https://user-images.githubusercontent.com/7886280/142647045-e396c119-503d-4a3c-8e9b-3c86bb438622.png)!

### Submission checklist

*Once the issue is submitted, please check items in this list as you add under ‘Additional project info’*

- [ ] Link to your project: could be a code repository, a shared document, etc.

- [ ] Goals for the Brainhack: describe what you want to achieve during this brainhack. 

- [ ] Skills: list skills that would be particularly suitable for your project (coding and non-coding).

**Comment by StanSStanman** [comment]
Dear @SylvainTakerkart,
we added your project on the BHM2021 website. :tada: 
Please check if all the information are correct, and tell us if you would like to change something.
Ruggero

**Comment by SylvainTakerkart** [comment]
@StanSStanman thanks!

I would just like to change the end, which starts by "This is a python project", coz this will scare potential participants... Can you replace with the following please?

"This is a project where coding is not required. If you know or have electrophysiology data recorded in animal models, come over and tell us about it!!!! Some other project participants might do some coding, in python"

@JuliaSprenger do you have comments / wishes?

**Comment by JuliaSprenger** [comment]
Hi @StanSStanman, thanks for integrating the project on the website. My only comment would be that there is a `)` missing at the end of the text. Everything else reads nicely.

**Comment by JuliaSprenger** [comment]
Hi have another comment regarding the global timeline. I don't think its clear that the first hacking and Python intro session will be held in parallel from the way they are listed in the table. Maybe it would be better to make two separate rows for the events and explicitly label them as `track 1` and `track 2` or `parallel session 1` and `parallel session 2`?

**Comment by StanSStanman** [comment]
Hi @SylvainTakerkart  and @JuliaSprenger 
All the modification that you suggested are now online!

See ya! :cowboy_hat_face:

**Comment by dumaatravaie** [comment]
Ok
