### ISSUE TITLE
BrainSpread: Misfolded proteins spreading

### ISSUE THREAD

**Issue by AleksandraPestka** [Brainhack-Marseille/brainhack-marseille.github.io#12]
## Project info

**Title:**
BrainSpread: Misfolded proteins spreading 

**Project lead and collaborators:**
Alessandro Crimi (lead)
Luca Gherardini
Aleksandra Pestka

**Description:**
Most of neurodegenerative diseases are believed to be related to the spreading of misfolded proteins. Controversies still arise whether which path those proteins follow, and whether brain structures are damaged during this spreading or they were predisposing it.

In the project, DWI data collected from Alzheimer's patients is used. The data flow includes: preprocessing, tractography generation, connectivity matrix calculation and connectivity graph visualization. 
The next step is to simulate a spreading of misfolded proteins based on generated connectivity matrix and the location of seeds for Alzheimer's  beta-amyloid in the brain. 

**Goals for Brainhack Marseille**
- discuss and code the simulation methods (heat kernel based diffusion, epidemic simulation model etc.). 
- discuss the problem of a connectome structure change in time caused by neurodegeneration 

**Skills:**
Non-coding skills: knowledge of neuroimaging, simulation modeling
Coding skills: Python programming

**Striking Image**
![2021_11_23_0ne_Kleki](https://user-images.githubusercontent.com/39761584/143028811-436477b3-9f02-4247-bea0-07ef0d7f4850.png)

**Comment by AleksandraPestka** [comment]
hi @Brainhack-Marseille/project-monitors: My project is ready!

**Comment by StanSStanman** [comment]
Dear @AleksandraPestka ,
we added your project on the BHM2021 website. :tada: 
Please check if all the information are correct, and tell us if you would like to change something.
Ruggero

**Comment by dumaatravaie** [comment]
hi @AleksandraPestka , Are you participating in person or by online ( Vidio conference ) ? Anyway, thank you for your participation in BrainHack. 
Dipankar

**Comment by AleksandraPestka** [comment]
@dumaatravaie In person

**Comment by dumaatravaie** [comment]
> @dumaatravaie In person

Very Good, See you soon ...

**Comment by mszinte** [comment]
Dear @AleksandraPestka ,
Thank you for your submission to the brainhack marseille. 
We highly recommend you to also submit your project on the brainhack global website.
To do so, you must fill up this form: 
https://github.com/brainhackorg/global2021/issues/new?assignees=&labels=project&template=project-submission-template.yml
Thanks,
