### ISSUE TITLE
Going beyond pairwise interactions by digging into Higher-Order Interactions

### ISSUE THREAD

**Issue by EtienneCmb** [Brainhack-Marseille/brainhack-marseille.github.io#13]
## Project info

**Title:**
Going beyond pairwise interactions by digging into Higher-Order Interactions

**Project lead and collaborators:**
Etienne Combrisson (@EtienneCmb), Andrea Brovelli (@brovelli) and Daniele Marinazzo (@danielemarinazzo)

Twitters :
@kNearNeighbors, @BrovelliAndrea, @dan_marinazzo

**Description:**

Modern theories suggest that cognitive functions emerge from the dynamic coordination of neural activity over large-scale and hierarchical networks. Currently, the characterization of a network and therefore, the functional interactions between brain regions, is usually performed using metrics of Functional Connectivity (FC). FC analysis is mostly based on the quantification of statistical relations between pairs of brain regions. However, pairwise interactions are probably insufficient to explain the emergence of more complex brain network interactions, such as during goal-directed learning tasks. Here, we propose to move beyond pairwise interactions by studying at Higher Order Interactions (HOI) i.e. quantifying the information carried by groups of "over-two" brain regions (= multiplets). As a first step, a framework called [O-information](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.100.032305) (= Information about Organizational structure) was recently proposed to characterize redundancy- and synergy-dominated systems. This framework has recently been extended with the [dOinfo](https://www.frontiersin.org/articles/10.3389/fphys.2020.595736/full) (= dynamic Information about Organizational structure) to quantify how multiplets of variables carry information about the future of the dynamical system they belong to. This dOinfo extension allows to separate multiplets of variables which influence synergistically the future of the system from redundant multiplets.

Since (d)OInfo frameworks are recent, the math underneath are quite new and we are not necessary familiar with it. The overall goal of this project is to understand the methods by looking at the reference papers and the Python / Matlab implementations of both (d)OInfo.

**Goals for Brainhack Marseille**

During this BainHack, we will :
1. Go through the reference papers (i.e. [Rosas et al. 2019](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.100.032305) and [Stramaglia et al. 2021](https://www.frontiersin.org/articles/10.3389/fphys.2020.595736/full)) to build an intuition of the math undergoing the HOI
2. Go through the Python toolbox [HOI_toolbox](https://github.com/PranavMahajan25/HOI_toolbox) to understand what are the input / output types, to identify the main accessible functions such as understanding the internals
3. Make the package easy to install, probably clean up so files
4. Identify whether there are coding bottlenecks that could be easily solved to speed up computations (soft Numba, multi-core, tensor-computations etc.)

If we still have time, here are some new features that could be added to the Python toolbox :
1. Implementation of false discovery rate for the significance of the multiplets
2. Speed up of the bootstrap
3. Include some plotting functions

**Skills:**

Computational : 70%
Information-theory : 60%
Math : 50%
Python : 70%
Matlab : 30%

**Striking Image**
![doinfo](https://user-images.githubusercontent.com/15892073/143055839-8f85b60b-b94f-4bc4-8c88-ecaf35f724f2.png)

**Comment by EtienneCmb** [comment]
Beau gosse @StanSStanman the project is ready !

**Comment by StanSStanman** [comment]
Dear Beau Gosse @EtienneCmb,
we are sorry, but your project was refused by the BHM commission :sob: 
You're going further beyond our beauty standard! :1st_place_medal: 
Jokes aside:
we added your project on the BHM2021 website. :tada: 
Please check if all the information are correct, and tell us if you would like to change something.
Ruggero

**Comment by dumaatravaie** [comment]
Beau Gosse inside
Moche Gosse outside 

As like

Intel Inside joke

**Comment by brovelli** [comment]
Please add

Skills:

Fluent Italian : 67%
