### ISSUE TITLE
Macapype: external pipelines

### ISSUE THREAD

**Issue by davidmeunier79** [Brainhack-Marseille/brainhack-marseille.github.io#14]
## Project info

**Title:**
Macapype: external pipelines

**Project lead and collaborators:**
David Meunier 
Kepkee Loh
Julien Sein
Bastien Cagna
Olivier Coulon

**Description:**
Macapype is a python package based on nipype, wrapping the tools required for NHP MRI anatomical segmentation. Macapype provide several processing pipelines, allowing optimisation and adaptation, depending on the quality of the images (SNR), acquisition sequences and antenna types, as well as species.
Today, macapype is provided as a github repo, a pip install, and a docker/singularity image. The accepted inputs have to be in BIDS format, and macapype pipelines are callable thanks to a command line interface (CLI). 

**Links :**
Macapype Github: https://github.com/Macatools/macapype
Macapype Documentation: https://macatools.github.io/macapype/index.html

**Goals for Brainhack Marseille**
Macapype is mostly oriented to PNH anatomical segmentation. However, many applications can be included starting from a good segmentation quality : 
    • ACT (anatomically contrained tractography) from diffusion data, 
    • mesh and surfaces generation
that are not pure PNH but that are useful to be linked to macapype segementation. We would like to discuss the possibility of integration o this tools as external pipelines, i.e. not directly part of macapype, but that can be added in global workflows based on nipype.

**Putative schedule :**
Monday 6th of December , 2pm (Central Europe Time): presentation of macapype, past and future functionalities
Tuesday 7th of December, 2pm (CET) : diffusion and tractography of PNH data : discussion , and strategies

**Good first issues :**
Wrapping in nipype a script to reorient anatomical image to normalized orientation

**Required skills :**
PNH anatomical MRI processing 30-100 %
python 50-100 %
nipype 30-100 %

**Striking Image**
![macapype_logo_manon](https://user-images.githubusercontent.com/7290245/143407460-dee2115d-feb6-4089-b514-f2d19deef17b.jpg)

**Comment by StanSStanman** [comment]
Dear @davidmeunier79,
we added your project on the BHM2021 website. :tada: 
Please check if all the information are correct, and tell us if you would like to change something.
Ruggero
