### ISSUE TITLE
SLAM: a python package for neuroanatomical surfaces analysis and modeling

### ISSUE THREAD

**Issue by alexpron** [Brainhack-Marseille/brainhack-marseille.github.io#15]
## Project info

**Title:**

Development of the SLAM -Surface anaLysis And Modeling- python package

**Project lead and collaborators:**
 
**Project lead:** Guillaume Auzias and Alexandre Pron (@AlexandrePron) will be the project managers during this brainhack.
**Project collaborators:** Main developers are the members of the MeCA team (http://meca-brain.org/), and we are welcoming warmly external collaborators, contributors and users.

**Description:**

Slam (https://brain-slam.github.io/slam/) is an open source python package dedicated to the representation of neuroanatomical surfaces stemming from MRI data in the form of triangular meshes and to their processing and analysis.

Main features include read/write gifti (and nifti) file format, geodesic distance computation, several implementations of graph Laplacian and Gradient, mesh surgery (boundary identification, large hole closing), several types of mapping between the mesh and a sphere, a disc… Have a look at the examples on the documentation website: https://brain-slam.github.io/slam/auto_examples/index.html

**Goals for Brainhack Marseille**

+ to further improve the documentation 
+ to further improve the code quality of slam 's core functions (code linting, docstrings, refactoring, utils module)
+ to further improve code quality with new unitest and potential speed-up of specific pieces of code such as for instance the computation of the curvature
+ to help potential users to get familiar with this python package
+ brainstorm about slam perimeter 
+ design a logo 
we are of course also open if new features are proposed from the contributors

**Skills:**

 python 50%, mesh processing 20%, will to share ideas and good time 100% .
Minimal skills in python coding and github are required, but various levels of expertise are welcome since some of our objectives can be addressed with limited coding effort such as augmenting the documentation and designing slam logo

**Striking Image**

![shape_index](https://user-images.githubusercontent.com/45215023/143565090-9f25f51f-d201-4283-a573-df5972549667.png)
### Submission checklist

*Once the issue is submitted, please check items in this list as you add under ‘Additional project info’*

- [x] Link to your project: could be a code repository, a shared document, etc.

- [x] Goals for the Brainhack: describe what you want to achieve during this brainhack. 

- [x] Skills: list skills that would be particularly suitable for your project (coding and non-coding).

**Comment by alexpron** [comment]
hi @Brainhack-Marseille/project-monitors: My project is ready!

**Comment by StanSStanman** [comment]
Dear @alexpron,
we added your project on the BHM2021 website. :tada: 
Please check if all the information are correct, and tell us if you would like to change something.
Ruggero

**Comment by alexpron** [comment]
Dear beau gosse @StanSStanman. Thank you very beaucoup for the add. The information is fine ! I would to modify few things:
In the goals for the BrainHack section
1. add right under the title: 
Tasks and objectives we would like to achieve can be found in the [brain-slam github project](https://github.com/orgs/brain-slam/projects/1)
2. Put the bullet point to "help potential users to get familiar with this python package" first  and add after. The first BrainHack day could be considered as a training session for slam users.
Thank you very beaucoup in advance 
Alex

**Comment by StanSStanman** [comment]
Hello @alexpron, 
your projet description have been modifié.
Hope that tu trouveras les changes to your goût.
See you bientôt.

Ruggero

**Comment by alexpron** [comment]
Super @StanSStanman thank you. See you
