### ISSUE TITLE
16s Metagenomic analysis of Gut Microbiome 

### ISSUE THREAD

**Issue by dumaatravaie** [Brainhack-Marseille/brainhack-marseille.github.io#18]
### Title

16s Metagenomic analysis of Gut Microbiome 

### Leaders

Dipankar Bachar

### Brainhack Global 2022 Event

Brainhack Marseille

### Project Description

16S rRNA gene sequencing is commonly used for identification, classification and quantitation of microbes within complex biological mixtures such as environmental samples and gut samples. Many studies [1][2] are trying to establish the link between the intestinal microbiota with different neurodevelopment, neurogical disorders etc. In these studies the BioInformatic analysis of the data coming from gut samples plays a very important role. So, in our brainhack project we will work on the publicly available data from one of these article[1]. So, this project is aimed for those who are interested in the BioInformatic analysis of Gut Microbiota and are also interested in the different pipelines and analysis tools like QIIME2[4] , cutadapt[5] , Kraken2[6] etc.

In this project, we propose:
    To go through this [1] article to understand their method of analyzing the gut microbiota
    To download their 16s sequencing data from NCBI ( submitted by the authors ) 
    To extract and filter the data 

For advanced users, We also propose:
    To write( Python ) few tools for filtering the sequencing data
    To try to create an Anaconda environment or a Singularity image with the 16s analysis pipeline QIIME2[4]
    To try to implement some of the methods of analysis with QIIME2 ( as described in the article )
    To understand the importance of reproducibility of the results

References :

[1] The microbial metabolite p-Cresol induces autistic-like behaviors in mice by remodeling the gut microbiota
Patricia Bermudez-Martin et al.

[2]  Gut Microbiota Regulate Motor Deficits and Neuroinflammation in a Model of Parkinson's Disease
Timothy R Sampson  et al.

[3] https://lcsciences.com/16s-rrna-gene-sequencing-for-identification-classification-and-quantitation-of-microbes/

[4] Reproducible, interactive, scalable and extensible microbiome data science using QIIME 2
Evan Bolye et al.
    
[5] https://cutadapt.readthedocs.io/en/stable/
    
[6] https://ccb.jhu.edu/software/kraken2/

### Link to project repository/sources

https://github.com/dumaatravaie/BrainHack_Marseille_2022_16s

### Goals for Brainhack Global

The goal of this project to have a basic idea about how the BioInformatics analysis of 
16S rRNA sequences are done and also to familiarize with different freely available tools and pipelines 
used for the analysis. 

### Good first issues

- Installation of anaconda and create a conda environment
- Creation of Image Singularity

### Communication channels

https://mattermost.brainhack.org/brainhack/channels/brainhack_marseille_2022_16s_metagenomic

### Skills

Anaconda or Singularity 50%
Python 50%
Unix/Linux 25%
Basic knowledge about 16s sequencing 25%

### What will participants learn?

They will have the basic idea about how the BioInformatic analysis of 16s metagenomic data are done. They will have a preliminary idea about how to search, download and use the open source sequence data from NCBI. They will also learn about many of the state of art open source software tools and pipelines ( which are used for the analysis of 16s data ).

### Number of collaborators

2

### Credit to collaborators

All of the collaborators or participants will have equal credit ...

### Image

![image](https://user-images.githubusercontent.com/9570817/199976131-f9ccaa3d-ee11-4ebc-8c62-86281e589e21.png)

### Type

other

### Development status

0_concept_no_content

### Topic

reproducible_scientific_methods, other

### Tools

other

### Programming language

Python, `R`, shell_scripting, unix_command_line

### Modalities

not_applicable

### Git skills

4_not_applicable

### Anything else?

This is a BioInformatics project where we will focus on a published article and will work on the data submitted by the authors to a public data repository ( NCBI ) ...

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [ ] Twitter-sized summary of your project pitch.

**Comment by dumaatravaie** [comment]
Hi @brainhackorg/project-monitors my project is ready!

**Comment by StanSStanman** [comment]
Thank you @dumaatravaie for submitting your project to BrainHack Marseille 2022! :tada::tada::tada:
Your project have been added to our website.

Ruggero for the BHM team.

**Comment by dumaatravaie** [comment]
Thank you @StanSStanman , but i can't see it yet ..

**Comment by dumaatravaie** [comment]
:-D , Thank you, I can see it now ...

**Comment by StanSStanman** [comment]
It was made on purpose for you to update your browser every 3 minutes!
Jokes aside, it is now on, maybe it will take some time to update :wink:

**Comment by dumaatravaie** [comment]
@Remi-Gau , my project is ready for BrainHack Global ..
