### ISSUE TITLE
LFP and single units decoding in rats performing a distance estimation task

### ISSUE THREAD

**Issue by FaberCapitano** [Brainhack-Marseille/brainhack-marseille.github.io#19]
### Title

LFP and single units decoding in rats performing a distance estimation task

### Leaders

Fabrizio Capitano, Pierre-Yves Jacob.

### Collaborators

Fabrizio Capitano, Pierre-Yves Jacob, Celia Laurent, Francesca Sargolini.

### Brainhack Global 2022 Event

Brainhack Marseille

### Project Description

Navigating in space requires to continuously updating the representation of its own position in the environment. In poorly cued environments (e.g. in darkness) this can only be done by estimating the direction and the distance in order to compute a vectorial integration of the movement (so called path-integration). In a set of studies in rats we demonstrated that the entorhinal cortex plays a fundamental role in path integration. However, how the circuit infers the running distance is yet to be known. Using a distance estimation task, we discovered that the theta oscillations of the local field potential and the firing pattern of single neurons in the entorhinal cortex correlate with the running distance estimated by the rats. But how much and how well the unitary and the field activity allow the circuit to infer about the travelled distance?
In the context of the BrainHack Marseille 2022, we would like to interact and collaborate with people with a good knowledge of neural decoding of EEG-LFP and/or unitary activity in order to implement proper methods to decode the estimated running distance starting from a dataset of electrophysiology recordings in behaving rats. The final goal will be to quantify the information carried by population and single units activity within the entorhinal circuit.

### Link to project repository/sources

blank

### Goals for Brainhack Global

-	Discuss about pros and cons of different decoding methods;
-	Sort-out the most appropriate one(s) for our project;
-	Start implementing the analysis on the dataset;
-	More in general, seeding future collaborations.

### Good first issues

-	Here you’ll find some of our previous studies to have more insight about the neuroscientific framework of the project (https://pubmed.ncbi.nlm.nih.gov/28161726/, https://pubmed.ncbi.nlm.nih.gov/30783085/).

### Communication channels

https://distanceestim-7gc4659.slack.com/archives/C0484F29VUP

### Skills

Neural decoding 100%
EEG/LFP and single units 80%
Spatial cognition 50%

### What will participants learn?

The scientific project has already a solid background in terms of hypothesis, dataset acquisition and analysis. Participants will take advantage of the strong expertise of the other collaborators in the domain of the brain circuits of the spatial cognition.

### Number of collaborators

1

### Credit to collaborators

According to the issue of the collaboration the collaborators could be credited in future scientific publications.

### Image

Leave this text if you don't have an image yet.

### Type

method_development

### Development status

0_concept_no_content

### Topic

neural_decoding

### Tools

other

### Programming language

Matlab

### Modalities

behavioral, EEG, other

### Git skills

0_no_git_skills

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [X] Twitter-sized summary of your project pitch.

**Comment by StanSStanman** [comment]
Thank you @FaberCapitano for submitting your project to BrainHack Marseille 2022! :tada::tada::tada:
We ask you to add to this issue an image for your project, it should be descriptive but also captivating for potential participants! :wink: 
In the meanwhile, your project has been added to our website (with a default icon).

Ruggero for the BHM team.

**Comment by FaberCapitano** [comment]
Hello. Sorry for the late answer. Here the image for the project. I'd like just to ask a small modification on the project informations. Would it possible to add Jean-Yves Montenay as a contributors of the project?
Best
Fabrizio
![Fig for brainhack](https://user-images.githubusercontent.com/116893048/202428256-e46e8edc-185c-4822-89dc-30e8ec576db1.jpg)
