### ISSUE TITLE
eCobidas: because methods writing is too important (and boring) to let humans do it!

### ISSUE THREAD

**Issue by Remi-Gau** [Brainhack-Marseille/brainhack-marseille.github.io#2]
## Project info

**Title:**
eCOBIDAS: a webApp to that writes your methods section for you

**Project lead:**
- Rémi Gau
- Brainhack Mattermost: @remi-Gau
- Twitter: [@RemiGau](https://twitter.com/RemiGau) 

**Project collaborators:**
Many ! And hopefully even more after you join !
All contributors are listed on the repository [HERE](https://github.com/Remi-Gau/eCobidas#contributors-) and in this [spreadsheet](https://docs.google.com/spreadsheets/d/1v_ReviQZLNxg9T5qCYAfMiA-rZupMnWp03PSNVRGpBI/edit?usp=sharing)

I try to keep the spreadsheet up to date at every event and I plan to use it to automate making a longer "Contributors" page for the repository. 

**Registered Brainhack Global 2020 Event:**
- Donostia
- Marseille

**Project Description:**
The main aim of this project is to improve reporting methods and results in neuroimaging (f/MRI, i/EEG, MEG, PET...) in order to increase transparency and reproducibility.

We want to do this by developing a set webapps to run checklists:
- based on best practices guidelines and recommendation of a field
- that are both easy and practical to use, 
- that provides a machine readable summary of an experiment and its analysis
- that can then automatically generate parts of the methods section.

**Data to use:**
No data will be used.

**Link to project repository/sources:**
Main repository: https://github.com/Remi-Gau/eCobidas

Documentation: https://remi-gau.github.io/eCobidas/

fMRI prototype app: 
 - repo: https://github.com/ohbm/cobidas
 - webApp: https://ohbm.github.io/cobidas/#/

PET prototype app: 
 - repo: https://github.com/Remi-Gau/cobidas-PET
 - webApp: https://remi-gau.github.io/cobidas-PET/#/

eyetracking prototype app: 
 - repo: https://github.com/Remi-Gau/cobidas-eyetracker
 - webApp: https://remi-gau.github.io/cobidas-eyetracker/#/

**Goals for Brainhack Global 2020:**

**Good first issues:**

Several "good first issues" [here](https://github.com/Remi-Gau/eCobidas/labels/good%20first%20issue) but I would like to focus on:

1. Making sure the documenation is understandable and constitute good on-board and How-To materieal
2. Create some prototype script / toy example that can take the output of the app and generate a method section

**NOTE** : I created empty issued where I want to describe better the goals of those 2 issues.

**Required skills:**

The project has many moving parts so there is a certain level of flexibility in terms of skills needed: this is why the we indicate ranges of skill requried

- A certain love for handling and tidying up spreadsheets (20-100 %) :heart: :bookmark_tabs: 
- Domain specific knowledge (in EEG, MEG, MRI...) (20-100 %)
- Writing documentation (0-40 %) :page_facing_up: 
- Git / Github (0-50 %) :computer: 
- Linked data (0-50 %) :1234: 
- Python (0-20 %) :snake: 
- Javascript (0-20 %) :chart_with_upwards_trend: 

the source of the project starts in [several spreadsheets](https://drive.google.com/drive/u/0/folders/1ydwALHDzl21dcef3qhkju8JKKAT3Y72V) that are then read by a python script to create the questions for the webApp

**Communication channels:**
On mattermost: https://mattermost.brainhack.org/brainhack/channels/cobidas_checklist

 

**Project labels**

- [x] I added all of the labels I want associated to my project

### Submission checklist

*Once the issue is submitted, please check items in this list as you add under ‘Additional project info’*

- [x] Link to your project: could be a code repository, a shared document, etc.

- [x] Goals for Brainhack Global 2020: describe what you want to achieve during this brainhack.

- [x] Flesh out at least 2 “good first issues”: those are tasks that do not require any prior knowledge about your project, could be defined as issues in a GitHub repository, or in a shared document.

- [x] Skills: list skills that would be particularly suitable for your project. We ask you to include at least one non-coding skill. Use the issue labels for this purpose.

- [x] Chat channel: A link to a chat channel that will be used during the Brainhack Global 2020 event. This can be an existing channel or a new one. We recommend using the [Brainhack space on Mattermost](https://mattermost.brainhack.org/).

Optionally, you can also include information about:

- [ ] Number of participants required.

- [ ] Twitter-size summary of your project pitch.

- [x] Provide an image of your project for the Brainhack Global 2020 website. 

I need to work on a better one than that (that could be part of this project actually), but here you go: Image: 

![ ](https://raw.githubusercontent.com/Remi-Gau/eCobidas/master/docs/img/checklist.jpg)

![ ](https://raw.githubusercontent.com/Remi-Gau/eCobidas/remi-logo/inputs/logos/logo.png)

We would like to think about how you will credit and onboard new members to your project. If you’d like to share your thoughts with future project participants, you can include information about:

- [x] Specify how you will acknowledge contributions (e.g. listing members on a contributing page).

- [x] Provide links to onboarding documents if you have some: the documentation is the closest thing I have to an onboarding document at the moment -  https://remi-gau.github.io/eCobidas/

**Comment by StanSStanman** [comment]
Hi!
Thank you for submitting your project to Brainhack Marseille 2020.
Your project has been added to the BHM2020 web page (https://brainhack-marseille.github.io/index.html). Please check the relative information and let us know if everything is fine.
We ask you especially to check the 'Required skills' part, that will be used by the participants to better orient toward the most fitting project. You can indicate up to four needed skills with a percentage number indicating the level of demanded expertise. 
Moreover we suggest you to provide a stronger striking image that can:
1) represent at the best your project
2) attract collaborators during this event

We are very glad for your participation!
Looking forward to work with you,
The BHM2020 team.

**Comment by EtienneCmb** [comment]
Hi @Remi-Gau,

I have a suggestion about a more representative picture of your project : you could take a screenshot of a spreadsheet / csv to show how the informations are centralized and organized and also add the eCOBIDAS logo?

**Comment by Remi-Gau** [comment]
> We ask you especially to check the 'Required skills' part, that will be used by the participants to better orient toward the most fitting project. You can indicate up to four needed skills with a percentage number indicating the level of demanded expertise.

I added some range of required skills on this issue. Let me know if this is OK. Do you think I should also add it in the first good issues on my own repo?

**Comment by Remi-Gau** [comment]
> Hi @Remi-Gau,
> 
> I have a suggestion about a more representative picture of your project : you could take a screenshot of a spreadsheet / csv to show how the informations are centralized and organized and also add the eCOBIDAS logo?

I don't have a logo but let me try to conjure something up quickly.

**Comment by Remi-Gau** [comment]
> Hi @Remi-Gau,
> 
> I have a suggestion about a more representative picture of your project : you could take a screenshot of a spreadsheet / csv to show how the informations are centralized and organized and also add the eCOBIDAS logo?


Added a second image. It is a bit more abstract...But it has brains on it. :wink:

what do you think?

**Comment by EtienneCmb** [comment]
@Remi-Gau the figure is nice and explicit IMO !

**Comment by EtienneCmb** [comment]
> > We ask you especially to check the 'Required skills' part, that will be used by the participants to better orient toward the most fitting project. You can indicate up to four needed skills with a percentage number indicating the level of demanded expertise.
> 
> I added some range of required skills on this issue. Let me know if this is OK. Do you think I should also add it in the first good issues on my own repo?

Not sure to understand the question, do you mean assign a "good first issue" in the labels?

**Comment by Remi-Gau** [comment]
> Not sure to understand the question, do you mean assign a "good first issue" in the labels?

Ah sorry: I went too fast.

For example in this "first good issue" on my repo, should I list the skills too? 

https://github.com/Remi-Gau/eCobidas/issues/178

**Comment by EtienneCmb** [comment]
> > Not sure to understand the question, do you mean assign a "good first issue" in the labels?
> 
> Ah sorry: I went too fast.
> 
> For example in this "first good issue" on my repo, should I list the skills too?
> 
> [Remi-Gau/eCobidas#178](https://github.com/Remi-Gau/eCobidas/issues/178)

I think it's ok, at least for our side we have everything we need to finalize your project on the webpage. Thank you !
