### ISSUE TITLE
SLAM - A pure python package for Surface anaLysis And Modeling

### ISSUE THREAD

**Issue by alexpron** [Brainhack-Marseille/brainhack-marseille.github.io#20]
### Title

SLAM - A pure python package for Surface anaLysis And Modeling

### Leaders

- Guillaume AUZIAS : @AuziasGuillaume/guillaume.auzias
- Alexandre PRON: @AlexandrePron/alexp

### Brainhack Global 2022 Event

Brainhack Marseille

### Project Description

Slam (https://brain-slam.github.io/slam/) is an open source python package dedicated to the representation of neuroanatomical surfaces stemming from MRI data in the form of triangular meshes and to their processing and analysis.

Main features include read/write gifti (and nifti) file format, geodesic distance computation, several implementations of graph Laplacian and Gradient, mesh surgery (boundary identification, large hole closing), several types of mapping between the mesh and a sphere, a disc...
Have a look at the examples on the documentation website: https://brain-slam.github.io/slam/auto_examples/index.html

### Link to project repository/sources

https://github.com/brain-slam/slam

### Goals for Brainhack Global

- to improve the documentation of basic core functions and modules (e.g. ```the curvature.py``` module)
- to increase unit test coverage and quality of basic core functions and modules
- to  speed-up specific pieces of code such as the computation of the curvatures
- to help potential users to get familiar with this python package depending on their use cases

### Good first issues

1. issue one: https://github.com/brain-slam/slam/issues/89

### Communication channels

https://mattermost.brainhack.org/brainhack/channels/slam

### Skills

-  will to share ideas and good time: 100%
-  code documentation: 80%
- GitHub workflows: 10%
- scientific python (e.g. numpy): 20 % 
- mesh processing: 10%
- 
 Various levels of expertise are welcome since some of our objectives can be addressed with no coding effort (documentation) and others require advanced knowledge of numpy (code speed-up)

### Onboarding documentation

https://github.com/brain-slam/slam/blob/master/README.md

### What will participants learn?

- clean python code documentation 
- working according to github workflow for a scientific project
- code profiling and optimization (for code speed up)
- continuous integration and unit test (for code speed up)

### Number of collaborators

3

### Credit to collaborators

Project contributors are listed on the project README using all-contributors 

### Image

![slam](https://user-images.githubusercontent.com/45215023/200366131-7edb0adc-d2c5-4f24-9bd2-d11f26bad065.png)

### Type

coding_methods, documentation

### Development status

2_releases_existing

### Topic

other

### Tools

other

### Programming language

Python

### Modalities

MRI

### Git skills

1_commit_push

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [X] Twitter-sized summary of your project pitch.

**Comment by alexpron** [comment]
Hi @brainhackorg/project-monitors my project is ready!

**Comment by StanSStanman** [comment]
Thank you @alexpron  for submitting your project to BrainHack Marseille 2022! :tada::tada::tada:
Your project have been added to our website.

Ruggero for the BHM team.
