### ISSUE TITLE
Viewing the world in third-person - experimental considerations for a successful study

### ISSUE THREAD

**Issue by jeremy-fgn** [Brainhack-Marseille/brainhack-marseille.github.io#21]
### Title

Viewing the world in third-person - experimental considerations for a successful study

### Leaders

Jérémy Faggion

### Brainhack Global 2022 Event

Brainhack Marseille

### Project Description

- What are you doing, for whom, and why?
- I am conceiving an experiment to study the implications of living with a third-person point of view on mental states and self-awareness. For self-awareness implications, see for instance research from [Olaf Blanke](https://academic.oup.com/brain/article/127/2/243/347826). I expect positive implications for users, including increased self awareness and increased focus, and interesting implications for users undergoing temporary stress or anxiety. If the issue of learning to associate somatosensory information to the new way of seeing the world can be solved, this could open the door to many more experiments around metacognition, but also around learning involving perception and movement of the body. Inspired by the study of Hubert Dolezal in 1982, using prism glasses to experience the world upside-down.

- What makes your project special and exciting?
- Visuo-tactile association in third-person point of view is hard to achieve. The challenge revolves around how to make the brain learn that association. One candidate approach is to start from a first-person point of view and gradually transition to a third-person point of view, using a camera transmitting its video feed to a headset worn by the user. Existing solutions exist for drone piloting (FPV goggles).

- How to get started?
- Identify the bottlenecks to come. Propose a design solution to allow for a gradual transition from first-person to third-person point of view. Experiment with FPV goggles and bring them to the Brainhack :)
The outcome of this project should be in the form of schematics, prototypes, pseudocode, people to reach out to and a list of resources to take inspiration from.

- Where to find key resources?
- By typing "fpv goggles third person" in a search engine
- https://petapixel.com/2014/07/02/custom-built-oculus-rift-gopro-rig-lets-experience-life-third-person/
- https://www.youtube.com/watch?v=anE3RNf_3s0

### Link to project repository/sources

[Google Docs](https://docs.google.com/document/d/1jN9d5g_HwmBDktQSOZDhtqTnUc2ZP8Vvep4LntVyueI/edit?usp=sharing)

### Goals for Brainhack Global

The outcome of this project should be in the form of schematics, pseudocode, people to reach out to and a list of resources to take inspiration from.
Iteration cycles should be as short as possible.
Testing should ideally happen on-site during the hackathon.

### Good first issues

1. Gradual transition from 1st person to 3rd person - engineering task

2. Visuo-tactile association in shifted or novel ways of viewing the world - literature review task

3. Getting your hands on a drone and FPV goggles - engineering task

4. Identifying if using a stereo camera will prove crucial - literature review task

### Communication channels

Direct messaging app - TBD

### Skills

- sensorimotor association: 40%
- engineering and coding: 30%
- fast iteration mindset: 20%
- VR technologies: 10%

### What will participants learn?

Sensorimotor association, mental states, self-awareness, engineering and coding, and iterating fast

### Number of collaborators

3

### Credit to collaborators

Names engraved on a block of cheese and fed to seaguls

### Image

https://art-u1.infcdn.net/articles_uploads/0/811/3rd%20person%20real%20life.jpg

### Type

method_development

### Development status

0_concept_no_content

### Topic

other

### Tools

other

### Programming language

not_applicable

### Modalities

behavioral

### Git skills

0_no_git_skills

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [X] Twitter-sized summary of your project pitch.

**Comment by StanSStanman** [comment]
Thank you @jeremy-fgn for submitting your project to BrainHack Marseille 2022! :tada::tada::tada:
We are sorry but at the current state of submission your project can't be added on our website.
In detail, we need you to:
 - rewrite a more accessible project description, that contains essential information to understand the aim of your project (preferably as a plain text instead of bullet points)
 - add a captivating figure for your project
You can take some example from the current projects added on our website, or from those of past editions.
Your project will be published as soon as we receive these updates.
Thank you! :pray: 

Ruggero for the BHM team.

**Comment by jeremy-fgn** [comment]
@StanSStanman

**Comment by StanSStanman** [comment]
Thanks @jeremy-fgn your project have been updated on the website!

Ruggero for the BHM team.
