### ISSUE TITLE
Neural encoding of acoustic features during speech and music perception: traduction of matlab code into python

### ISSUE THREAD

**Issue by DCP-INS** [Brainhack-Marseille/brainhack-marseille.github.io#22]
## Title

Neural encoding of acoustic and semantic features during speech and music perception: Matlab to Python code translation

## Leaders

Bruno Giordano (INT) :
https://github.com/brungio/bhack_td
https://twitter.com/brungio
https://framateam.org/blgnatsou/messages/@bruno.giordano

Giorgio Marinato (INT) :
https://github.com/neurogima
https://twitter.com/neurogima
mattermost: @neurogima

## Collaborators

Benjamin Morillon (CR INS - https://github.com/DCP-INS)
Nadège Marin (IE, INS)
Arnaud Zalta (PhD student, INS)

## Brainhack Global 2022 Event

Brainhack Marseille

## Project Description

In everyday life, humans are particularly attuned to listening to two particular types of sound: speech and music. We apply a novel analysis method to shed light on how the brain is almost effortlessly able to use acoustic features to assign meaning to sounds. To do so, we use an original cross-validated Representational Similarity Analyses (RSA) approach implemented in Matlab to estimate the similarity between acoustic or semantic features of an auditory stream (speech, music) and neural activity (here intracranial EEG recordings decomposed into frequency bands).

## Link to project repository/sources

https://github.com/brungio/bhack_td

## Goals for Brainhack Global

The main goal of this project is to translate the Matlab code into Python:
- translate the temporal folding on the neural signal in Python
- identify the python libraries to calculate different distances metrics
- translate the cross-validation method
- implement native plotting using the Python libraries (e.g. Seaborn, matplotlib, etc)

## Good first issues

- identify python libraries that can speed up the code translation effort

## Communication channels

https://mattermost.brainhack.org/brainhack/channels/brainhack_marseille_2022_speech_music_representation

## Skills

python coding
Representational Similarity Analyses (RSA)
Cross-validation (train-test-validate)
intracranial EEG signal processing
sharing data analyses ideas

## What will participants learn?

to analyse intracranial EEG data
to perform cross-validation procedures to estimate the neural encoding of different acoustic features

## Data to use

We will provide a sample of a dataset of iEEG recordings.

## Number of collaborators

from 3 to 10

## Credit to collaborators

Acknowledgment in the code and in the Github repo.

## Image

Leave this text if you don't have an image yet.

## Type

pipeline_development

## Development status

1_basic structure

## Topic

neural_decoding

## Tools

MNE, RSAtoolbox (github.com/rsagroup/rsatoolbox), Scikit Learn

## Programming language

Python, Matlab

## Modalities

intracranial EEG

## Git skills

Basic git workflow: fork, branches, commit and pull request

**Comment by DCP-INS** [comment]
hey Ruggero,
thanks for the feedback.
I updated the project description (+ few other sections) by editing the
text directly in the github website (hope it's okay...).
But how can I update an image? I attached the figure that I'd like to add.

thanks
bn

Le mar. 8 nov. 2022 à 17:09, Ruggero Basanisi ***@***.***> a
écrit :

**Comment by StanSStanman** [comment]
Hi @DCP-INS, your project has been added on the website, we assigned you a default image. If you want to change it you can upload an image in a comment of this issue just dragging and dropping it in the text window.

Ruggero for the BHM team.

**Comment by DCP-INS** [comment]
merci Ruggero.
see u later

**Comment by StanSStanman** [comment]
You're welcome, please do not close the project until the end of the event, this can be used by participants to have further details!

**Comment by DCP-INS** [comment]
Ruggero, could you please add the following figure to our description?
thanks!

![bhack_td](https://user-images.githubusercontent.com/31863272/203986648-18f4d2cf-a510-4bae-9935-5f6547efc140.png)
