### ISSUE TITLE
Guidelines for tractography in primates

### ISSUE THREAD

**Issue by melinacordeau** [Brainhack-Marseille/brainhack-marseille.github.io#23]
### Title

Guidelines for tractography in primates

### Leaders

Mélina Cordeau (https://twitter.com/CordeauMelina)

### Collaborators

David Meunier 
Julien Sein
Arnaud Le Troter
https://mattermost.brainhack.org/brainhack/channels/bhg22-marseille-orga

### Brainhack Global 2022 Event

Brainhack Marseille

### Project Description

Create guidelines i.e. summarize all the important things to know, step by step, to make a good tractogram edition for non-human primate species. A document that would bring together all the parameters that are similar and those that differ between species for preprocessing and tractography. We will focus on marmosets, macaques, baboons and chimpanzees.

### Link to project repository/sources

https://colab.research.google.com/drive/1ZABRmtdCtYSdnUxdOiIatfU6VE_hq7iw#scrollTo=gJr_9dXGpJ05

### Goals for Brainhack Global

#1. Definition of guidelines based on human best practices
#2. Creation of a parameter file for each primate species
#3. Implementation of a corresponding Wiki in PRIME-RE platform

### Good first issues

- BATMAN tutorial: https://osf.io/fkyht/
- QSIPREP and QSIRECON: https://qsiprep.readthedocs.io/en/latest/
- PRIME-RE wiki: https://github.com/PRIME-RE/prime-re.github.io/wiki/Diffusion-processing

### Communication channels

https://mattermost.brainhack.org/brainhack/channels/bhg22-marseille-nhpdwi

### Skills

- DWI data skills: 75%
- Python coding: 25%
- Be friendly, tolerant, and inclusive: 100%

### What will participants learn?

Participants will exchange their expertise, learn to recognize/implement the best ways to proceed in order to achieve a correct tractogram in non-human primates.

### Number of collaborators

4

### Credit to collaborators

Participants will be credited on the Wiki page for their contributions.

### Image

<img width="584" alt="dwi_PNH" src="https://user-images.githubusercontent.com/64094058/200571160-6679aa78-b281-44ed-9ca4-f90f817bb558.PNG">

### Type

documentation

### Development status

0_concept_no_content

### Topic

diffusion, tractography

### Tools

Freesurfer, FSL, MRtrix

### Programming language

Python

### Modalities

DWI

### Git skills

0_no_git_skills

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [X] Twitter-sized summary of your project pitch.

**Comment by StanSStanman** [comment]
Thank you @melinacordeau for submitting your project to BrainHack Marseille 2022! :tada::tada::tada:
Your project have been added to our website.

Ruggero for the BHM team.
