### ISSUE TITLE
Inferring task-related higher-order interactions from brain network signals

### ISSUE THREAD

**Issue by EtienneCmb** [Brainhack-Marseille/brainhack-marseille.github.io#24]
### Title

Inferring task-related higher-order interactions from brain network signals

### Leaders

- Etienne Combrisson (Twitter : @kNearNeighbors)
- Andrea Brovelli (Twitter : @BrovelliAndrea)

### Collaborators

- Daniele Marinazzo (Twitter : @dan_marinazzo)
- Matteo Neri

### Brainhack Global 2022 Event

Brainhack Marseille

### Project Description

A central hypothesis in neuroscience posits that cognitive functions emerge from complex interactions between multiple brain regions. Similarly, cognitive deficits due to trauma or neurological conditions, such as after stroke, crucially depend on network-level alterations that disrupt normal interactions among multiple brain areas. Although central, progress towards testing these hypotheses has been limited by the lack of approaches for studying interactions between multiple brain regions beyond pairwise relations, the so-called higher-order interactions (HOIs). The aim of our project is to build a novel approach based on recent advances in information theory (the O-information metric) to infer task- or condition-specific HOIs (functional HOIs) from brain signals. We will explore the possibility to combine O-information estimates with permutation-based statistics implemented in [Frites](https://github.com/brainets/frites)

### Link to project repository/sources

# Toolboxes

- [HOI toolbox 2021](https://github.com/brainets/hoi_bhk)
- [Frites](https://github.com/brainets/frites)

# Papers

-  [Rosas et al. 2019](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.100.032305) 
- [Stramaglia et al. 2021](https://www.frontiersin.org/articles/10.3389/fphys.2020.595736/full)

### Goals for Brainhack Global

The main goal of this BrainHack is to have a working first version of the task-related HOI

### Good first issues

1. Prototype the main function (i.e. define input and output types, write down important internal steps)
2. Make it works in the non-dynamic case
3. Investigate the use of [Jax](https://github.com/google/jax) to speed up computations
4. Be able to simulate data with a known amount of redundancy and synergy

### Communication channels

[TO BE ADDED]

### Skills

Computational : 70%
Information-theory : 60%
Math : 50%
Python : 70%

### What will participants learn?

They will learn about : 
- Information-theoretic terminology (redundancy, synergy, mutual information, entropy)
- Conceptual differences between pairwise and higher-order interactions
- Non-parametric statistics

### Number of collaborators

4

### Credit to collaborators

Collaborators will be added to our [Frites' Hall of Fame](https://brainets.github.io/frites/overview/ovw_community.html#authors-and-contributors)

### Image

![201880960-8965350b-067f-4079-a64d-b482eb704f36](https://user-images.githubusercontent.com/15892073/202182218-f527ce37-773d-4591-b259-194c8211766d.png)

### Type

method_development

### Development status

1_basic structure

### Topic

information_theory

### Tools

other

### Programming language

Python

### Modalities

behavioral, ECOG, EEG, MEG

### Git skills

0_no_git_skills, 1_commit_push

### Things to do after the project is submitted and ready to review.

- [ ] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [ ] Twitter-sized summary of your project pitch.

**Comment by EtienneCmb** [comment]
@brovelli and @danielemarinazzo
- I let you check this first version
- @danielemarinazzo do you have a nice striking image we could use?

**Comment by danielemarinazzo** [comment]
![image](https://user-images.githubusercontent.com/5311102/201878843-82863ccc-1e17-46dc-925e-892f2668eb9b.png)

![image](https://user-images.githubusercontent.com/5311102/201879213-ce330848-015b-4ae7-8d7d-1df663864a3f.png)

**Comment by brovelli** [comment]
file:///home/INT/brovelli.a/Downloads/hoi.png

**Comment by brovelli** [comment]
![hoi](https://user-images.githubusercontent.com/19585963/201880960-8965350b-067f-4079-a64d-b482eb704f36.png)

**Comment by brovelli** [comment]
This figure is taken from https://www.nature.com/collections/bbahggjjga

**Comment by StanSStanman** [comment]
Thank you @EtienneCmb for submitting your project to BrainHack Marseille 2022! :tada::tada::tada:
Your project have been added to our website. Ciao BG!

Ruggero for the BHM team.

**Comment by danielemarinazzo** [comment]
Hi there
we recently added some stuff to the [matlab repo](https://github.com/danielemarinazzo/HOI), in particular the proper bootstrap for the lagged computations, and the implementation of the [gradients of HOIs](https://arxiv.org/abs/2207.03581).

Ping me here (or by email/whatsapp/slack (is there a channel for this?) whatevs) if you need input these days, or send me a link if you have an open zoom room where I can just pop in.

**Comment by brovelli** [comment]
Here is the mattermost
https://mattermost.brainhack.org/brainhack/channels/bhg22-marseille-hoi
