### ISSUE TITLE
PsychophyGit - a fast and flexible tool for online experiments

### ISSUE THREAD

**Issue by hugoladret** [Brainhack-Marseille/brainhack-marseille.github.io#27]
### Title

PsychophyGit - a fast and flexible tool for online experiments

### Leaders

Hugo Ladret (Twitter : @hugoladret)
Jean-Nicolas Jérémie (Twitter : @JnJerem)

### Collaborators

Laurent Perrinet (Twitter : @laurentperrinet)

### Brainhack Global 2022 Event

Brainhack Marseille

### Project Description

Acquiring human behavioural data through the Internet is on the rise, especially since the COVID-19 events. Often most, researchers looking for a way to set up online experiments will find themselves either using a) complex and tool-specific paradigms or b) to develop their own web code to suit their specific needs.
For this Brainhack project, we aim to develop a **fast** and **flexible** tool which would allow anyone to perform custom **psychophysical** investigations through the web. For their convenience, users will be generating their own stimuli locally, uploading them into a GitHub repo, and we will develop a tool which will allow reliable online procedures to be deployed using their stimuli.

### Link to project repository/sources

https://github.com/JNJER/PsychophyGit

### Goals for Brainhack Global

* Develop Python code that allows to deploy psychophysical experiments with light requirements (python skills) 
* Develop a server-side interface which parses GitHub repos to get experimental stimuli (javascript skills)
* Create simple 2 Alternative Forced Choice tasks (psychophysics skills)

### Good first issues

* Parsing git repos to get stimuli
* Creating a web browser-based interface
* Generate RGPD compliant data parsing

### Communication channels

https://framateam.org/int-marseille/channels/brainhack2022_psychophygit 

### Skills

- Python coding : 70 %
- Javascript coding : 50 %
- Psychophysics : 30 % 

### What will participants learn?

- How to manage server-side Python code
- How to interface Python script with Javascript GUI
- Have a fun time on a fun project !

### Number of collaborators

2

### Credit to collaborators

Project contributors are listed on the project README using the all-contributors github bot. 
In case any scientific production would stem from the project, all project contributors would be adequately listed as authors.

### Image

![image](https://user-images.githubusercontent.com/16063162/203026153-ee45563a-5ea0-4f43-833c-b2633e5bcbb1.png)

### Type

method_development

### Development status

0_concept_no_content

### Topic

systems_neuroscience, other

### Tools

other

### Programming language

Python

### Modalities

behavioral

### Git skills

1_commit_push

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [X] Twitter-sized summary of your project pitch.

**Comment by hugoladret** [comment]
Hi @brainhackorg/project-monitors ; @StanSStanman , our project is ready !

**Comment by StanSStanman** [comment]
Thank you @hugoladret  for submitting your project to BrainHack Marseille 2022! :tada::tada::tada:
Your project have been added to our website.

Ruggero for the BHM team.
