### ISSUE TITLE
DIGLaB : DIGital Lab Book

### ISSUE THREAD

**Issue by fredbarthelemy** [Brainhack-Marseille/brainhack-marseille.github.io#3]
## Project info

**Title:**
DIGLaB : DIGital Lab Book

**Project lead and collaborators:**
Fred Barthelemy, Sylvain Takerkart, Julia Sprenger

**Description:**
The goal of this project is to provide an user-friendly digital alternative to the classical lab book to the experimentalists working with non-human primates. The advantage of a digital version of the notebook are plenty:
- Can be read by automatic process for storage of comments or metadata
- Can help to automatize the writing of information in a click
- Can help to adopt future INT (or other) standards easily (e.g. filenames)
- Can be printed in case of need
- Avoid fastidious decoding of someone else's handwriting

**Goals for Brainhack Marseille**
- Present the current version
- Get feedback from future users
- Provide personalized versions to the users that want to use it
- Develop a tool for automatice metadata collection from saved DIGLaBs

**Skills:**
Doing experiments 70%, Javascript 50%, Python 50%

**Striking Image**
![DIGLaB](https://user-images.githubusercontent.com/12963386/99665194-95515480-2a69-11eb-865f-2998fb441ee1.png)

### Submission checklist

*Once the issue is submitted, please check items in this list as you add under ‘Additional project info’*

- [ ] Link to your project: could be a code repository, a shared document, etc.

- [x] Goals for the Brainhack: describe what you want to achieve during this brainhack. 

- [x] Skills: list skills that would be particularly suitable for your project (coding and non-coding).

**Comment by fredbarthelemy** [comment]
@EtienneCmb @StanSStanman My project is ready

**Comment by EtienneCmb** [comment]
@fredbarthelemy @SylvainTakerkart @JuliaSprenger  Your project has been added to the website : https://brainhack-marseille.github.io/#project3

Let me know if everything is ok for you  !

++
