### ISSUE TITLE
Sulcilab: A collaborative sulci labelling web app

### ISSUE THREAD

**Issue by BastienCagna** [Brainhack-Marseille/brainhack-marseille.github.io#30]
### Title

Sulcilab: A collaborative sulci labelling web app

### Leaders

Bastien Cagna (Neurospin, Paris)

### Brainhack Global 2022 Event

Brainhack Marseille

### Project Description

Sulcilab is a web base application to mannually labelize sulcal graphs (outputs of BrainVISA).
I propose this project with 2 goals:

           1. Get feedback from beta users
           2. Propose to develop a javascript based package to provide a 2D/3D viewer for neuroimaging

- How to get started?
Ask me to create an account for you and then go to [ http://babalab.fr:3000]( http://babalab.fr:3000) to test the app.

- Where to find key resources?
[Github project](https://github.com/BastienCagna/sulcilab)
[ThreeJS docs](https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene)
[React docs](https://reactjs.org/docs/hello-world.html)

### Link to project repository/sources

https://github.com/BastienCagna/sulcilab

### Goals for Brainhack Global

- Get feedback from beta testers
- Build an independent 3D viewer dedicated to brain

### Good first issues

1. issue one: report bugs

### Communication channels

https://mattermost.brainhack.org/brainhack/channels/bhg22-sulcilab

### Skills

No particular skills are need to help. It only require to have a computer with internet access to test.

For development, the project is based on Python (using FastAPI) and Typescript (using React).

### What will participants learn?

Brain Anatomy
Web Development

### Number of collaborators

3

### Credit to collaborators

Projects contributors will be listed in the README.md and involved in future publications depending on their level of implication.

### Image
![logo_sillons](https://user-images.githubusercontent.com/22853356/204153285-41e35cda-cc23-492a-8dfe-3f749c320edf.png)

### Type

visualization

### Development status

1_basic structure

### Topic

data_visualisation

### Tools

other

### Programming language

Python, javascript

### Modalities

MRI

### Git skills

0_no_git_skills

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [X] Twitter-sized summary of your project pitch.

**Comment by BastienCagna** [comment]
Hi @brainhackorg/project-monitors my project is ready!

**Comment by StanSStanman** [comment]
Thank you @hugoladret for submitting your project to BrainHack Marseille 2022! :tada::tada::tada:
Your project have been added to our website.

Ruggero for the BHM team.
