### ISSUE TITLE
Removing pink noise (1/f) in LFP across different electrophysiological recording systems

### ISSUE THREAD

**Issue by lauralopezgaldo** [Brainhack-Marseille/brainhack-marseille.github.io#31]
### Title

Removing pink noise (1/f) in LFP across different electrophysiological recording systems

### Leaders

Laura LÓPEZ GALDO, Shrabasti JANA, Camila LOSADA, Hasnae AGOURAM, Cléo SCHOEFFEL, Nilanjana NANDI

### Brainhack Global 2022 Event

Brainhack Marseille

### Project Description

- What are you doing, for whom, and why?
- What makes your project special and exciting?
- How to get started?
- Where to find key resources?

We will try to remove the aperiodic noise found in the spectrum of the LFP data using the _fooof_ module (https://github.com/fooof-tools/fooof). We will parametrize our signals, the aperiodic and periodic components and make some comparison across the different frequency bands. 

We have data from EEG human recordings, LFP monkey utah array recordings and monkey laminar intracranial recordings across different areas. We want to see the effect of pink noise in each of the different setups and try to clean the signal.

Some related literature can be found in the following links:

- Parametrizing aperiodic component: https://doi.org/10.1038/s41593-020-00744-x
- Gamma-Beta frequency interactions: www.pnas.org/cgi/doi/10.1073/pnas.1710323115 and 10.1162/jocn_a_01600

### Link to project repository/sources

https://github.com/lauralopezgaldo/Brainhack-Marseille-2022

### Goals for Brainhack Global

- Working together with different datasets
- Compare the different results
- Share the analysis code

### Good first issues

1. Get the spectrum from the raw data

2. Parametrize the 1/f

3. Frequency band comparison

### Communication channels

https://mattermost.brainhack.org/brainhack/channels/bhg22-marseille-pinknoise

### Skills

- python coding: 70%
- sharing ideas: 60%
- electrophysiological data: 100%
- literature review: 30%

### What will participants learn?

Participants will learn to parametrize the spectrum of electrophysiological data and undertand the meaning of pink noise.

### Number of collaborators

more

### Credit to collaborators

Everyone will be able to use the data we have and we'll make the code open for everyone.

### Image

![image](https://user-images.githubusercontent.com/44520889/204252282-aea67e58-00c8-4dc3-85f0-0b15a0ef8e07.png)

### Type

coding_methods, pipeline_development

### Development status

0_concept_no_content

### Topic

neural_encoding

### Tools

Jupyter, MNE

### Programming language

Python

### Modalities

EEG, other

### Git skills

1_commit_push

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [ ] Twitter-sized summary of your project pitch.

**Comment by lauralopezgaldo** [comment]
Hi @brainhackorg/project-monitors my project is ready!

**Comment by StanSStanman** [comment]
Thank you @lauralopezgaldo for submitting your project to BrainHack Marseille 2022! :tada::tada::tada:
Your project have been added to our website.

Ruggero for the BHM team.
