### ISSUE TITLE
Decoding Fiber photometry & Rat behavior

### ISSUE THREAD

**Issue by MayaIwilliams** [Brainhack-Marseille/brainhack-marseille.github.io#32]
### Title

Decoding the bulk signal from fiber photometry during rat behavior  

### Leaders

Maya Williams, Mickael Degoult, Christelle Baunez

### Collaborators

Nicolas Maurice, Lucie Vignal

### Brainhack Global 2022 Event

Brainhack Marseille

### Project Description

- What are you doing, for whom, and why?
   I am collecting calcium signals from Infalimbic, Prelimbic, and Anterior cingulate projection terminals at the subthalamic nucleus (STN) using fiber photometery. The goal is to look at the signal from these regions during sucrose and cocaine self administration, to discover the role of these pathways in food vs cocaine intake. In addition, we would focus on discrete behavior during the trails ( lever pressing, reward delivery, error responses) to study the signals of these pathways during both sucrose and cocaine intake. 

- What makes your project special and exciting?
  It will be the first time the hyperdirect pathway is studied in such detail, looking at the mulitpule cortical projection the STN and comparing their roles in food vs cocaine rewards. From perovious work in the lab, we know that STN lesions have opposite effects on cocaine and food intake, increasing food intake while decreasing cocaine intake. This study will explore the much less studies hyperdirect pathway and its role in addiction like behaviors so that the STN can be consided a target for theraputic treatment in addiction, without harming a persons natural motivations for food. 
- How to get started?
 I have collected data from sucrose taking rats, and addapted an open souce code to fit my data. I next need help on further analysis, combinding results into groups, and doing statistical analysis. 
- Where to find key resources?
 some codes I have used or wish to try:
 https://www.nature.com/articles/s41598-021-03626-9
https://pubmed.ncbi.nlm.nih.gov/31680685/

### Link to project repository/sources

https://github.com/MayaIwilliams/Fiber_processing % my data and modified code
https://github.com/LernerLab/GuPPy % GUI developed by a different lab. I have not tested yet

### Goals for Brainhack Global

increase matlab literacy OR switch to python
save output and compare traces 

### Good first issues

1. issue one: How is my code? can i make it more simple

2. issue two: How is the GUI working, can I use it for my data?

### Communication channels

NA

### Skills

80% matlab coding 
20% teaching for dummies 

### What will participants learn?

Fiber photometry techniques and signal processing 

### Number of collaborators

1

### Credit to collaborators

project contibuters will be listed in Readme 

### Image

Leave this text if you don't have an image yet.
![ratcutie](https://user-images.githubusercontent.com/118851397/204302380-158a4dcd-957f-4148-b29f-eacf030c2efa.jpg)

### Type

coding_methods, method_development

### Development status

1_basic structure

### Topic

neural_decoding, other

### Tools

other

### Programming language

Matlab, Python

### Modalities

other

### Git skills

0_no_git_skills

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [ ] Twitter-sized summary of your project pitch.

**Comment by StanSStanman** [comment]
Thank you @MayaIwilliams for submitting your project to BrainHack Marseille 2022! :tada::tada::tada:
Your project have been added to our website.

Ruggero for the BHM team.
