### ISSUE TITLE
In a scanner darkly: The next 50 years of neuroscience

### ISSUE THREAD

**Issue by jeanmichelhupe** [Brainhack-Marseille/brainhack-marseille.github.io#37]
### Title

In a scanner darkly: The next 50 years of neuroscience 

### Leaders

Hao Tam Ho
Jean-Michel Hupé

### Brainhack Global 2023 Event

Brainhack Marseille

### Project Description
To celebrate its 50th anniversary in 2020, the Society for Neuroscience (SfN) published an upbeat viewpoint on “The Next 50 years of Neuroscience”. Apart from the fact that the article reads like a blatant admission of SfN’s commitment to transhumanism, more worryingly, it exposes the society’s and, by extension, the field’s complete disengagement from reality. There is not a single reference to global warming in the article, which mirrors exactly the daily silence on environmental issues in neuroscience labs around the world. This has led us to suspect that either neuroscientists live in a parallel universe or climate change is pure science fiction.  
But hold on! Guilt-ridden and eco-anxious, a number of neuroscientists have recently published (in Neuron and Nature Reviews Neuroscience no less) recommendations on how to reduce the ecological impact of neuroscience research, demonstrating some awareness of what is going on outside the ivory tower. Incredulously, they claim that it is possible for neuroscience labs to "go green” by, e.g., stopping the exhausts from fume hoods when not in use and attending conferences and meetings virtually instead of flying there - all without affecting scientific output, of course. These uninspiring, unambitious and completely ineffective “mini” steps have the advantage of giving neuroscientists the illusion that they are contributing to mitigating rather than aggravating the ongoing environmental crisis. Thus, there is no need to question the objectives of neuroscientific research in the face of a potential ecological and societal collapse within possibly much less than 50 years. 
We think it is time for neuroscientists to face reality. Therefore, we propose to write an opinion piece for a major neuroscience journal where we want to clearly and honestly discuss the challenges for the community in this time of ecological and socio-political upheaval. To our knowledge, such a publication does not exist yet. Moreover, we hope to convince the Brainhack community as a whole to support our project, which would send a strong signal to the rest in the field. 
We shall start by reading and reacting to the three references listed below. Other key resources will include reports related to climate change and planetary boundaries, as can be retrieved from the IPCC and IPBES websites, for example. If needed, the organisers will present an up-to-date summary of the ecological situation to ensure that all participants are equally well informed. The workshop will follow a "world café" framework where all ideas, reflections and facts useful to the paper shall be discussed in order to bring about a consensus on the content and organisation of the article. The writing of each part will be done in sub-groups with ongoing rotations for the revisions. All participants will be listed as co-authors of the paper. The two organisers will be responsible for finishing up the paper, submitting it and so on. But any participant will be welcome to join this "steering committee" after the workshop. 

### Link to project repository/sources

https://www.jneurosci.org/content/40/1/101.abstract
https://www.sciencedirect.com/science/article/pii/S0896627320301422
https://www.nature.com/articles/s41583-020-0311-5

### Goals for Brainhack Global

Milestones :
(1) list of issues, arguments or facts that we may bring in the paper
(2) consensusual short list of what we will put in the paper
(3) organized list (paper skeleton)
(4) first draft of the paper

### Good first issues

1. issue one: ecological crisis

2. issue two: meaning of research in neuroscience

### Communication channels

https://mattermost.brainhack.org/brainhack/channels/bhg23-marseille-next50yearsneuroscience
(replaces the previous framateam link)

### Skills

Curiosity
Responsibility
English reading
Wrtiting skills

### What will participants learn?

Participants will learn to think beyond their specialty and research project. They will learn from other disciplines. They will behave as a responsible citizen instead of just a scientist

### Number of collaborators

more

### Credit to collaborators

All contributors will be co-authors of the publication.

### Image

Leave this text if you don't have an image yet.

### Type

other

### Development status

0_concept_no_content

### Topic

other

### Tools

other

### Programming language

not_applicable

### Modalities

not_applicable

### Git skills

4_not_applicable

### Things to do after the project is submitted and ready to review.

- [ ] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [ ] Twitter-sized summary of your project pitch.

**Comment by arnaudletroter** [comment]
Thank you for submitting your project to BrainHack Marseille 2023.
Your project is now visible online !

Arnaud for The BHM organization team.
