### ISSUE TITLE
MYOnset: a Python package to detect EMG onset for electrophysiological studies 

### ISSUE THREAD

**Issue by lspieser** [Brainhack-Marseille/brainhack-marseille.github.io#38]
### Title

MYOnset: a Python package to detect EMG onset for electrophysiological studies 

### Leaders

Laure Spieser and Boris Burle
Laboratoire de Neurosciences Cognitives, Aix-Marseille University, CNRS

### Brainhack Global 2023 Event

Brainhack Marseille

### Project Description

Among brain’s functions, selecting and executing actions is certainly one of the most important. In this research domain, investigating electromyographic (EMG) activity of muscles involved in actions execution can be an easy way to collect more information on processes of interest. Yet, once EMG is recorded, one needs to process and analyse EMG data in addition to other collected data (e.g., behavior, electrophysiological recordings, etc). Particularly, the detection of EMG bursts onsets is often a critical processing step. However, few tools are available to achieve it, and none was really suitable to use in typical experimental designs of experimental psychology such as reaction time tasks. To meet this need, we developed MYOnset, a Python package designed to help such EMG recordings processing, with particular attention given to the step of EMG bursts onsets and offsets detection. 
MYOnset integrates tools for standard preprocessing of EMG recordings, like bipolar derivation and filtering. Regarding EMG onset detection, MYOnset proposes a two-steps method: first, an automatic detection of EMG bursts onsets and offsets, second, a step of visualization and manual correction of detected onsets and offsets. MYOnset integrates two algorithms combining different automatic detection methods. Further, MYOnset proposes a specific window for the visualization and manual correction step, which the most time-consuming step and for which no tool was available. This window offers an adapted view for EMG signals and the associated markers, i.e., experimental triggers and EMG onsets and offsets automatically detected. Importantly, user can interact with onset and offset markers to adjust onsets/offsets positions, insert new onsets/offsets, and remove existing onsets/offsets.
MYOnset package is available on PyPI (https://pypi.org/project/myonset/) and GitHub (https://github.com/lspieser/myonset). 

### Link to project repository/sources

https://github.com/lspieser/myonset

### Goals for Brainhack Global

- discuss package organisation
- implement new detection methods (e.g., bayesian changepoint detection)
- add code testing

### Good first issues

1. issue one:
none yet...
2. issue two:

### Communication channels

https://mattermost.brainhack.org/brainhack/channels/bhg23-marseille-myonset

### Skills

- python coding : 80%
- share ideas : 70%
- electrophysiology : 10%

### What will participants learn?

Just have fun together ! and learn on electromyography signal if you're interested

### Number of collaborators

1

### Credit to collaborators

Project contributors are listed on the project README

### Image

Leave this text if you don't have an image yet.

### Type

coding_methods

### Development status

2_releases_existing

### Topic

data_visualisation, physiology

### Tools

other

### Programming language

Python

### Modalities

other

### Git skills

0_no_git_skills

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [X] Twitter-sized summary of your project pitch.

**Comment by lspieser** [comment]
Hi @brainhackorg/project-monitors my project is ready!

**Comment by arnaudletroter** [comment]
Thank you for submitting your project to BrainHack Marseille 2023.
Your project is now visible online !

Arnaud for the BHM organization team.
