### ISSUE TITLE
Electronic laboratory notebook presentation (eLab)

### ISSUE THREAD

**Issue by killianrochet** [Brainhack-Marseille/brainhack-marseille.github.io#39]
### Title

Electronic laboratory notebook presentation and discussion (eLab)

### Leaders

-

### Collaborators

Sylvain Takerkart 
Simon Moré 
Killian Rochet

### Brainhack Global 2023 Event

Brainhack Marseille

### Project Description

eLab is an electronic laboratory notebook for researchers. Useful for the acquisition of different experimental data/ metadata. 

Contribution to no longer have a paper laboratory notebook. 
Useful for the data acquisition process by researchers. 
Is important in the data standardization process. 

You can find more information about eLabFTW here : https://www.elabftw.net

### Link to project repository/sources

https://github.com/elabftw/elabftw

### Goals for Brainhack Global

The aim is the presentation of an electronic laboratory notebook: eLab. Allowing the acquisition of experimental data/ metadata. 

This presentation will be followed by a general discussion on the use of laboratory notebooks and how to use them

In terms of time: we want to do this on Tuesday mornings starting at 9:30am

### Good first issues

-

### Communication channels

-

### Skills

-sharing ideas

### What will participants learn?

-electronic lab notebook
-different way to use it

### Number of collaborators

1

### Credit to collaborators

-

### Image

![elab](https://github.com/Brainhack-Marseille/brainhack-marseille.github.io/assets/74175986/6bed9297-0dad-46e4-b519-0c2a8686b56f)

### Type

data_management

### Development status

0_concept_no_content

### Topic

reproducible_scientific_methods

### Tools

other

### Programming language

not_applicable

### Modalities

not_applicable

### Git skills

0_no_git_skills

### Things to do after the project is submitted and ready to review.

- [ ] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [ ] Twitter-sized summary of your project pitch.

**Comment by arnaudletroter** [comment]
Thank you for submitting your project to BrainHack Marseille 2023.
Your project is now visible online !

Arnaud for The BHM organization team.
