### ISSUE TITLE
macapype: segmentation to mesh pipeline.

### ISSUE THREAD

**Issue by davidmeunier79** [Brainhack-Marseille/brainhack-marseille.github.io#4]
## Project info

**Title:**
macapype: segmentation to mesh pipeline.

**Project lead and collaborators:**
David Meunier @davidmeunier79 
Bastien Cagna @BastienCagna
Kep Kee Loh @kepkeeloh

Project channel during Brainhack Marseille 2020:

**Description:**
Macapype is an open source python package based on the nipype framework. Dedicated to the processing of NHP MRI data, Macapype brings together existing tools from popular neuroimaging softwares (e.g. FSL, ANTs, SPM, AFNI etc), and the wraps of specialised scripts for NHP MRI data processing. Currently, Macapype also provides predefined pipelines for the preprocessing, brain extraction, and segmentation of NHP MRI data that are easy to use, and customizable to various input file types (T1w or T1w/T2w). These segmentation pipelines have been successfully adapted to MR images from various NHP species, including the macaques, baboons and marmosets.

**External links** :
github : https://github.com/Macatools/macapype
documentation : https://macatools.github.io/macapype/index.html
mattermost user forum: https://framateam.org/macapype-users/channels/town-square (requires a framateam account)

**Goals for Brainhack Marseille**
In this brainhack, we would like to expand the existing pipelines of Macapype to allow the generation of surface meshes following the segmentation of the MR images. So far, macapype users have been performing the above process (i.e. surface mesh generation) by first, using a set of customised scripts to import Macapype-generated segmentations into Brainvisa, and second, to manually (point-and-click) generate surface meshes via the Morphologist Toolbox in Brainvisa. We aim to incorporate these two steps as an additional module in Macapype, which will enable the generation of surface meshes directly from the segmentations produced by Macapype. The final result would be a powerful pipeline that takes raw NHP structural MR scans as input, and generating tissue segmentation masks and surface meshes as outputs.

**Skills:**
-  python programming (20-100%)
- nipype coding and wrapping (0-100%)
- MRI data processing (50-100%)
- anyone that has NHP data to process (0-100%)

Related softwares : brainvisa, freesurfer, nipype

**Striking Image**

![macapype_illus](https://user-images.githubusercontent.com/7290245/100080647-5eeb4f00-2e46-11eb-902c-78acef2b6c55.jpg)

**Comment by EtienneCmb** [comment]
Thx @davidmeunier79 . Can you also provide a percentage describing each skill (e.g nipype 30% etc.)

**Comment by davidmeunier79** [comment]
@EtienneCmb I don't know if that makes sense but I have added percentages...

**Comment by EtienneCmb** [comment]
@davidmeunier79 percentages should reflect the prior knowledge of a skills in order to attend to your project. For example, if search for people that are quit strong in nipype you can let your 100%. But if moderate skills are required, set it to 50%

**Comment by StanSStanman** [comment]
Dear BrainHack Marseille 2020 participant, we are sorry to inform you that your project has been refused by the commission.
Just joking :smile:  @davidmeunier79 the project is on the website.
Let me know if it is ok for you!
See ya!

**Comment by davidmeunier79** [comment]
Grazie Ruggero @StanSStanman !
