### ISSUE TITLE
new project: Surf(ac)ing fMRI data

### ISSUE THREAD

**Issue by MatthieuGilson** [Brainhack-Marseille/brainhack-marseille.github.io#40]
### Title

Surf(ac)ing fMRI data

### Leaders

Matthieu Gilson (mattermost: @matgilson)
Julien Sein (mattermost: @julien.sein)
Jean-Luc Anton (mattermost: @jl-anton)
Andrea Bagante (mattermost: @andreabag)
Martin Szinte

### Brainhack Global 2023 Event

Brainhack Marseille

### Project Description

The goal of this project is to combine tools in a pipeline for surface-based analysis of fMRI data. Surface-based analysis is a powerful way to align data from different subjects and datasets ([https://www.nature.com/articles/s41598-020-62832-z](https://www.nature.com/articles/s41598-020-62832-z), [https://www.sciencedirect.com/science/article/abs/pii/S1361841512000357](https://www.sciencedirect.com/science/article/abs/pii/S1361841512000357)). Join us to test tools that will help you to analyze your own fMRI data at the whole-brain level!

The pipeline will combine open-science tools like fMRIprep, Workbench (from HCP), nilearn (Python library). We will provide a couple of subject data to benchmark the tools; they will be formatted in the BIDS format ([https://bids.neuroimaging.io/](https://bids.neuroimaging.io/)), which is a standard to share data. Experience in Python is recommended. You should install a Python distribution like Anaconda beforehand ([https://anaconda.org/](https://anaconda.org/)), we may also use MRI viewer like mango ([https://mangoviewer.com/](https://mangoviewer.com/)) and tools from Workbench ([https://humanconnectome.org/software/connectome-workbench](https://humanconnectome.org/software/connectome-workbench)).

### Link to project repository/sources

TBA

### Goals for Brainhack Global

- contribute to benchmarking of open-source tools in fMRI analysis
- contribute to promoting sharable open-source tools in local neuroscientific community, beyond the computational community

### Good first issues

1. issue one: tutorial of nilearn on surface analysis ([https://nilearn.github.io/stable/auto_examples/00_tutorials/index.html](https://nilearn.github.io/stable/auto_examples/00_tutorials/index.html))

2. issue two: find a good issue...

### Communication channels

https://mattermost.brainhack.org/brainhack/channels/bhg23-marseille-surfacing_fmri_data

### Skills

- python coding: 60%
- data manipulation: 40%

### What will participants learn?

- MRI data manipulation (including BIDS format)
- fMRI preprocessing (fmriprep, workbench)
- decoding (nilearn)

### Data to use

we will provide a few subjects as a testbed

### Number of collaborators

3

### Credit to collaborators

Collaborators will be added in the README file of the github repo

### Image

Leave this text if you don't have an image yet.

### Type

pipeline_development

### Development status

0_concept_no_content

### Topic

MR_methodologies, neural_decoding

### Tools

BIDS, fMRIPrep, Nipype

### Programming language

Python, unix_command_line

### Modalities

fMRI, MRI

### Git skills

1_commit_push

### Things to do after the project is submitted and ready to review.

- [ ] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [ ] Twitter-sized summary of your project pitch.

**Comment by arnaudletroter** [comment]
Thank you for submitting your project to BrainHack Marseille 2023.
Your project is now visible online !

Arnaud for The BHM organization team.
