### ISSUE TITLE
Building models that interpret neuroimaging data

### ISSUE THREAD

**Issue by maedoc** [Brainhack-Marseille/brainhack-marseille.github.io#41]
### Title

Building models that interpret neuroimaging data

### Leaders

Marmaduke Woodman

### Collaborators

*it's early days*

### Brainhack Global 2023 Event

Brainhack Marseille

### Project Description

- What are you doing, for whom, and why?

We are writing a new implementation of whole brain models oriented towards recent machine learning algorithms.  This implementation is for students & post docs who will come up with tomorrow's theory of brain (dys)function and need better tools for doing so.

- What makes your project special and exciting?

Our project is 🦄🦄🦄 because we are building fine-grained models of neural dynamics in entire cohorts where current whole brain models only maps coarse-grained statistics. 

- How to get started?

The package is being developed at https://github.com/ins-amu/vbjax and includes neural mass and field models, forward models for MEG/fMRI and some data fitting examples. 

For the brain hack we will use data from HCP MEG with Brainstorm based preprocessing; scripts at https://github.com/maedoc/friedchicken, but this is not so much the focus of the project.

- Where to find key resources?

More resources on the background of the modeling is available at https://thevirtualbrain.org and https://www.ebrains.eu/tools/the-virtual-brain. 

### Link to project repository/sources

https://github.com/ins-amu/vbjax

### Goals for Brainhack Global

- discuss use cases with potential users, even those unfamiliar with modeling
- help new users install and run examples
- extend existing set of models
- write new examples for data users have already prepared
- test deep neural network for more flexible time series modeling

### Good first issues

- https://github.com/ins-amu/vbjax/issues/11
- https://github.com/ins-amu/vbjax/issues/29
- https://github.com/ins-amu/vbjax/issues/7

### Communication channels

nothing for the moment

### Skills

- Brainstorming use cases, data features & models 50%
- Python coding & debugging 50%

### Onboarding documentation

https://github.com/ins-amu/vbjax#readme

### What will participants learn?

- how to run a whole-brain simulation
- how to use Jax & NumPyro, potentiall w/ GPUs
- how to optimize a model to fit data
- how to do Bayesian MCMC to find parameters consistent with data

### Data to use

We are using mostly data from HCP https://db.humanconnectome.org, 

- preprocessed connectomes and BOLD from EBRAINS (https://search.kg.ebrains.eu)
- MEG w/ Brainstorm based preprocessing (https://github.com/maedoc/friedchicken)

### Number of collaborators

2

### Credit to collaborators

https://github.com/ins-amu/vbjax/graphs/contributors

### Image

https://avatars.githubusercontent.com/u/6401490?s=48&v=4

### Type

method_development, other

### Development status

2_releases_existing

### Topic

bayesian_approaches, causality, connectome, deep_learning, machine_learning, neural_networks, reproducible_scientific_methods, statistical_modelling, systems_neuroscience

### Tools

Brainstorm, Jupyter, MNE, other

### Programming language

containerization, documentation, Matlab, Python

### Modalities

MEG, other

### Git skills

0_no_git_skills, 1_commit_push, 2_branches_PRs

### Things to do after the project is submitted and ready to review.

- [x] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [ ] Twitter-sized summary of your project pitch.

**Comment by maedoc** [comment]
Hi @brainhackorg/project-monitors my project is ready!

**Comment by arnaudletroter** [comment]
Hi Marmaduke, 
Thanks for submitting your project to BHM 2023.
Your project is now visible online !
Arnaud for The BHM organization team.
