### ISSUE TITLE
Across-scales Higher-Order neural interdependencies (acrhos)

### ISSUE THREAD

**Issue by brovelli** [Brainhack-Marseille/brainhack-marseille.github.io#44]
### Title

Across-scales Higher-Order neural interdependencies

### Leaders

Andrea Brovelli (https://twitter.com/BrovelliAndrea)
Etienne Combrisson (https://twitter.com/kNearNeighbors)

### Collaborators

Thomas Robiglio (https://twitter.com/thomrobiglio)
Matteo di Volo (https://sites.google.com/view/matteodivolo/home)

### Brainhack Global 2023 Event

Brainhack Marseille

### Project Description

How can we study the role of higher-order neural interdependencies within and across scales in the brain? Do perception and cognitive arise from higher-order neural interdependencies? Higher-order neural interdependencies (HOIs) are defined as interactions involving more than two neurons, neural populations or brain regions. Recently, the BraiNets team has developed a new tool for higher-order analyses on neural time series (https://github.com/brainets/hoi). The metrics are based on recent advances in information theory and network science, combined with efficient optimisation software (JAX). Participants from all backgrounds are welcome. Novices in the field may be able to familiarise with the metrics and Python toolbox. Advanced participants may take the opportunity to add novel metrics, functionalities, high-level scripts and optimisation tools. All participants may bring their own dataset and/or explore simulated data of spiking neural networks and networks of mean-field signals provided. The project has a GitHub repository (https://github.com/brainets/acrho), where we will share simulated data and the outcomes of the BrainHack as Jupyter Notebooks.

### Link to project repository/sources

https://github.com/brainets/hoi
https://github.com/brainets/acrho

### Goals for Brainhack Global

Share the theoretical and computational tools for higher-order analysis of neural data. Develop novel functionalities and script for optimised analysis on large datasets.

### Good first issues

1. issue one: Read the documentation of the HOI toolbox https://brainets.github.io/hoi/
2. issue two: Read important papers cited in the HOI documentation
3. issue two: Explore the dataset containing simulations in the https://github.com/brainets/acrho repository
4. issue two: Try writing Notebooks to perform HOI analyses on the dataset

### Communication channels

https://framateam.org/int-brainets/channels/brainhack_acrho_2023

### Skills

Python 90%
Information theory 50%

### What will participants learn?

Beginners: 1) learn the basic information theoretical notions and metrics; 2) run analysis on simulated data and extract HOIs.
Advanced: 1) contribute with novel metrics; 2) develop example Jupyter Notebooks with showcases on different types of brain data (resting-state fMRI, task-related MEG/iEEG)

### Data to use

The project contains two sets of data. 
In the first dataset (dataset 1) we simulated the activity of a biologically realistic spiking neural network composed of excitatory and inhibitory neurons. We recorded spike times, that can be uploaded through the jupyter notebook Read_spike_train.ipynb. We simulated the response to two different stimuli of different amplitude. This was done for a homogeneous network and for a network including cell-to-cell diversity in inhibitory neurons (see di Volo & Destexhe, Sci Rep 2021). There is a file README to help the reading of the data.
In the second dataset (dataset 2) we employed a 1D spatially extended model of connected mean field models with anatomical connectivity following data in primary visual cortex. We study the response to external stimulation of two different amplitudes. Also for this case, we collected data for mean fields of homogeneous neurons and for a model including cell-to-cell diversity (see di Volo & Destexhe, Sci Rep 2021). A jupyter notebook helps reading data and plotting the spatio-temporal response of the model.

### Number of collaborators

3

### Credit to collaborators

Contributors will be listed in the Github repository https://github.com/brainets/acrho

### Image

![image](https://github.com/Brainhack-Marseille/brainhack-marseille.github.io/assets/19585963/fba32e64-018e-4ea5-99ab-ddfe54515a56)

### Type

coding_methods, method_development, pipeline_development

### Development status

0_concept_no_content

### Topic

information_theory, neural_encoding, neural_networks, systems_neuroscience, other

### Tools

other

### Programming language

Python

### Modalities

behavioral, ECOG, EEG, fMRI, MEG

### Git skills

1_commit_push

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [X] Twitter-sized summary of your project pitch.

**Comment by arnaudletroter** [comment]
Hi Andrea,
Thank you for submitting your project to BrainHack Marseille 2023.
Your project is now visible online !

Arnaud for The BHM organization team.

**Comment by brovelli** [comment]
Thanks!
