### ISSUE TITLE
Developing a routine to analyse calcium

### ISSUE THREAD

**Issue by NicoWana** [Brainhack-Marseille/brainhack-marseille.github.io#45]
### Title

Developing a routine to analyse calcium signals

### Leaders

Elysa Crozat
Jose Jorge Ramirez Franco
Nicolas Wanaverbecq

### Brainhack Global 2023 Event

Brainhack Marseille

### Project Description

**- What are you doing, for whom, and why?**
Calcium signal analysis from neuronal population expressing GCaMP6 (GECaP)
For the team research project
To monitor and determine neuronal activity and modulation

- What makes your project special and exciting?
Combining FIJI/Image J package with python code to create a ffull integrated environement

- How to get started?
Python script to call and use Image J package

- Where to find key resources?
Image J developer site

### Link to project repository/sources

don't have

### Goals for Brainhack Global

Combine image J plugins into python code

### Good first issues

1. issue one:

2. issue two:

### Communication channels

Don't know. through Mattermost Brainhack channel

### Skills

Python
Java
Image J

### What will participants learn?

To code, generate a analysis suite

### Number of collaborators

2

### Credit to collaborators

Through github depositary

### Image

Leave this text if you don't have an image yet.

### Type

coding_methods, data_management, pipeline_development

### Development status

0_concept_no_content

### Topic

data_visualisation, physiology

### Tools

other

### Programming language

Java, Python

### Modalities

other

### Git skills

0_no_git_skills

### Things to do after the project is submitted and ready to review.

- [ ] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [ ] Twitter-sized summary of your project pitch.

**Comment by arnaudletroter** [comment]
Hi Nicolas 
Thank you for submitting your project to BrainHack Marseille 2023.
Your project is now visible online !

Arnaud for The BHM organization team.
