### ISSUE TITLE
Development of the SLAM -Surface anaLysis And Modeling- python package

### ISSUE THREAD

**Issue by gauzias** [Brainhack-Marseille/brainhack-marseille.github.io#6]
## Project info

**Title:**
Development of the SLAM -Surface anaLysis And Modeling- python package

**Project lead and collaborators:**
Main developers are the members of the MeCA team (http://meca-brain.org/), but we are welcoming warmly external collaborators, contributors and users.
Guillaume Auzias will be the project manager during this brainhack.

**Description:**
Slam (https://gauzias.github.io/slam/) is an open source python package dedicated to the representation of neuroanatomical surfaces stemming from MRI data in the form of triangular meshes and to their processing and analysis.

Main features include read/write gifti (and nifti) file format, geodesic distance computation, several implementations of graph Laplacian and Gradient, mesh surgery (boundary identification, large hole closing), several types of mapping between the mesh and a sphere, a disc...
Have a look at the examples on the documentation website: https://gauzias.github.io/slam/auto_examples/index.html

**Goals for Brainhack Marseille**
During this brainhack, our objectives are:

-to add as a new feature the algorithms for computing surface profiling as described in Li, K., Guo, L., Li, G., Nie, J., Faraco, C., Cui, G., Zhao, Q., Miller, L.S. and Liu, T., 2010. Gyral folding pattern analysis via surface profiling. NeuroImage, 52(4), pp.1202-1214. https://doi.org/10.1016/j.neuroimage.2010.04.263

-to improve the documentation with new examples to enrich the gallery (https://gauzias.github.io/slam/auto_examples/index.html), which helps a lot potential new users

-to switch the example codes from python script to Jupiter notebooks

-to further improve code quality with new unitest and potential speed-up of specific pieces of code such as for instance the computation of the curvature

-to help potential users to get familiar with this python package

-we are of course also open if new features are proposed from the contributors

**Skills:**
python 50%, mesh processing 20%, will to share ideas and good time 100%
Minimal skills in python coding and github are required, but various levels of expertise are welcome since some of our objectives can be addressed with limited coding effort such as augmenting the documentation.

**Striking Image**
![Image of mesh](https://gauzias.github.io/slam/_images/sphx_glr_example_curvature_003.png)

### Submission checklist

*Once the issue is submitted, please check items in this list as you add under ‘Additional project info’*

- [x ] Link to your project: could be a code repository, a shared document, etc.

- [x ] Goals for the Brainhack: describe what you want to achieve during this brainhack. 

- [ x] Skills: list skills that would be particularly suitable for your project (coding and non-coding).

**Comment by StanSStanman** [comment]
Salut Guillaume! @gauzias 
Your project has been added to the website.
Tell me if you want to change something.
See you!

**Comment by gauzias** [comment]
Thanks @StanSStanman!
All good!
